export const destinations = [
  {
    id: "japan",
    name: "Japan",
    flag: "🇯🇵",
    tagline: "Experience Cherry Blossoms, Tokyo Nights and Mount Fuji",
    shortTagline: "Where ancient tradition meets neon future",
    processingTime: "7–10 Business Days",
    startingFee: "$40",
    heroImage: "https://picsum.photos/seed/japan-fuji/1920/1080",
    cardImage: "https://picsum.photos/seed/japan-card/600/800",
    successRate: "96%",
    approvalTime: "5–7 Business Days",
    bestTime: "March–May, Oct–Nov",
    visaDuration: "15–90 Days",
    accentColor: "#E8435A",
    requirements: [
      "Valid passport with 6+ months validity",
      "Completed visa application form",
      "2 recent passport-size photographs",
      "Proof of accommodation (hotel bookings)",
      "Return flight tickets or itinerary",
      "Bank statements (last 3 months)",
      "Travel insurance with min. $50,000 coverage",
    ],
    documents: [
      { name: "Passport Copy", required: true },
      { name: "Application Form DS-160", required: true },
      { name: "Photos (2 × 2 inch)", required: true },
      { name: "Hotel Confirmation", required: true },
      { name: "Flight Itinerary", required: true },
      { name: "Bank Statement (3 months)", required: true },
      { name: "Travel Insurance", required: true },
      { name: "Employment Letter", required: false },
      { name: "Income Tax Returns", required: false },
    ],
    travelTips: [
      "Get a Suica card for seamless travel on public transport.",
      "Book cherry blossom accommodations 6 months in advance.",
      "Download Google Translate with Japanese offline pack.",
      "Carry cash — many places in Japan are still cash-only.",
      "Respect quiet zones in trains and public spaces.",
    ],
    embassy: {
      name: "Embassy of Japan, New Delhi",
      address: "4-7, Shantipath, Chanakyapuri, New Delhi 110021",
      phone: "+91-11-2687-6581",
      hours: "Monday–Friday: 9:00 AM – 5:30 PM",
    },
  },
  {
    id: "switzerland",
    name: "Switzerland",
    flag: "🇨🇭",
    tagline: "Alpine peaks, chocolate, and storybook villages await you",
    shortTagline: "Heaven above the clouds",
    processingTime: "10–15 Business Days",
    startingFee: "€80",
    heroImage: "https://picsum.photos/seed/swiss-alps/1920/1080",
    cardImage: "https://picsum.photos/seed/swiss-card/600/800",
    successRate: "92%",
    approvalTime: "8–12 Business Days",
    bestTime: "Dec–Mar (Ski), Jun–Sep (Hiking)",
    visaDuration: "Up to 90 Days (Schengen)",
    accentColor: "#FF4444",
    requirements: [
      "Valid passport with 3+ months beyond stay",
      "Schengen visa application form",
      "2 passport-size photographs",
      "Travel medical insurance (€30,000 min.)",
      "Proof of accommodation in Switzerland",
      "Proof of sufficient funds (€100/day min.)",
      "Return flight tickets",
    ],
    documents: [
      { name: "Passport (original + copy)", required: true },
      { name: "Schengen Application Form", required: true },
      { name: "Photos (35×45mm)", required: true },
      { name: "Travel Insurance", required: true },
      { name: "Hotel Bookings", required: true },
      { name: "Bank Statement (6 months)", required: true },
      { name: "Flight Tickets", required: true },
      { name: "Cover Letter", required: false },
      { name: "NOC from Employer", required: false },
    ],
    travelTips: [
      "Buy a Swiss Travel Pass for unlimited train, bus & boat travel.",
      "Swiss Francs are preferred — carry some cash.",
      "Book mountain cable cars in advance during peak season.",
      "Tip: Visit Lauterbrunnen for the most stunning valley views.",
      "Tap water in Switzerland is safe and delicious to drink.",
    ],
    embassy: {
      name: "Embassy of Switzerland, New Delhi",
      address: "Nyaya Marg, Chanakyapuri, New Delhi 110021",
      phone: "+91-11-4988-7888",
      hours: "Monday–Friday: 9:00 AM – 12:30 PM",
    },
  },
  {
    id: "france",
    name: "France",
    flag: "🇫🇷",
    tagline: "Romance, wine, art and the Eiffel Tower under the stars",
    shortTagline: "The city of love and endless elegance",
    processingTime: "10–15 Business Days",
    startingFee: "€80",
    heroImage: "https://picsum.photos/seed/paris-eiffel/1920/1080",
    cardImage: "https://picsum.photos/seed/france-card/600/800",
    successRate: "90%",
    approvalTime: "8–12 Business Days",
    bestTime: "April–June, Sep–Nov",
    visaDuration: "Up to 90 Days (Schengen)",
    accentColor: "#0055A4",
    requirements: [
      "Valid passport (3+ months beyond return date)",
      "Schengen visa application form",
      "Passport-size photographs (white background)",
      "Travel health insurance (€30,000 coverage)",
      "Proof of accommodation (hotel/Airbnb)",
      "Bank statements (last 3 months)",
      "Return air tickets",
    ],
    documents: [
      { name: "Passport (original + copy)", required: true },
      { name: "Schengen Application Form", required: true },
      { name: "2 Photographs", required: true },
      { name: "Health Insurance", required: true },
      { name: "Accommodation Proof", required: true },
      { name: "Bank Statement", required: true },
      { name: "Flight Itinerary", required: true },
      { name: "Cover Letter", required: false },
      { name: "Payslips (3 months)", required: false },
    ],
    travelTips: [
      "Book Louvre tickets online to skip the 2-hour queue.",
      "Use Navigo pass for unlimited metro/bus travel in Paris.",
      "Many museums are free on the first Sunday of each month.",
      "Learn a few phrases in French — locals appreciate the effort.",
      "Book Seine River cruises at sunset for best experience.",
    ],
    embassy: {
      name: "Embassy of France, New Delhi",
      address: "2/50-E, Shantipath, Chanakyapuri, New Delhi 110021",
      phone: "+91-11-2419-6100",
      hours: "Monday–Friday: 8:30 AM – 12:00 PM",
    },
  },
  {
    id: "italy",
    name: "Italy",
    flag: "🇮🇹",
    tagline: "Ancient ruins, pasta, Amalfi coast and Venetian canals",
    shortTagline: "A feast for every sense",
    processingTime: "10–15 Business Days",
    startingFee: "€80",
    heroImage: "https://picsum.photos/seed/italy-colosseum/1920/1080",
    cardImage: "https://picsum.photos/seed/italy-card/600/800",
    successRate: "91%",
    approvalTime: "8–12 Business Days",
    bestTime: "April–June, Sep–Oct",
    visaDuration: "Up to 90 Days (Schengen)",
    accentColor: "#009246",
    requirements: [
      "Valid passport with 3+ months validity",
      "Schengen visa application form",
      "Recent passport-size photographs",
      "Travel health insurance (€30,000+)",
      "Hotel/accommodation bookings",
      "Bank statements (last 3 months)",
      "Proof of travel purpose",
    ],
    documents: [
      { name: "Passport", required: true },
      { name: "Application Form", required: true },
      { name: "Photos (2×)", required: true },
      { name: "Travel Insurance", required: true },
      { name: "Hotel Booking", required: true },
      { name: "Bank Statement", required: true },
      { name: "Flight Tickets", required: true },
      { name: "Employment Letter", required: false },
      { name: "Sponsorship Letter", required: false },
    ],
    travelTips: [
      "Pre-book the Colosseum and Vatican Museums — they sell out fast.",
      "Validate your train ticket before boarding to avoid fines.",
      "Avoid tourist-trap restaurants — walk a block off the main square.",
      "Try aperitivo hour (6–8 PM) for free snacks with drinks.",
      "The Amalfi Coast is best explored by ferry, not road.",
    ],
    embassy: {
      name: "Embassy of Italy, New Delhi",
      address: "50-E, Chandragupta Marg, Chanakyapuri, New Delhi 110021",
      phone: "+91-11-2611-4355",
      hours: "Monday–Friday: 9:00 AM – 12:00 PM",
    },
  },
  {
    id: "dubai",
    name: "Dubai",
    flag: "🇦🇪",
    tagline: "Golden sands, glass towers and luxury beyond imagination",
    shortTagline: "Where the desert meets the future",
    processingTime: "3–5 Business Days",
    startingFee: "$90",
    heroImage: "https://picsum.photos/seed/dubai-skyline/1920/1080",
    cardImage: "https://picsum.photos/seed/dubai-card/600/800",
    successRate: "98%",
    approvalTime: "2–3 Business Days",
    bestTime: "November–March",
    visaDuration: "30–90 Days",
    accentColor: "#C8A400",
    requirements: [
      "Valid passport with 6+ months validity",
      "Completed UAE visa application",
      "Passport-size photograph (white background)",
      "Confirmed return air tickets",
      "Proof of hotel accommodation",
      "Bank statement (last 3 months, min. $3,000 balance)",
    ],
    documents: [
      { name: "Passport (colour scan)", required: true },
      { name: "UAE Visa Application", required: true },
      { name: "Photograph", required: true },
      { name: "Flight Tickets", required: true },
      { name: "Hotel Booking", required: true },
      { name: "Bank Statement", required: true },
      { name: "Travel Insurance", required: false },
      { name: "Salary Certificate", required: false },
    ],
    travelTips: [
      "Dress modestly in malls, souks and public spaces.",
      "The Dubai Metro is the cheapest way to reach the main attractions.",
      "Book Burj Khalifa At the Top at sunset for breathtaking views.",
      "Try authentic Emirati food at Al Fanar Restaurant.",
      "Avoid public displays of affection — it's against local law.",
    ],
    embassy: {
      name: "UAE Embassy, New Delhi",
      address: "EP-12, Chandragupta Marg, Chanakyapuri, New Delhi 110021",
      phone: "+91-11-2687-2100",
      hours: "Monday–Friday: 9:00 AM – 4:00 PM",
    },
  },
  {
    id: "australia",
    name: "Australia",
    flag: "🇦🇺",
    tagline: "Great Barrier Reef, Outback adventures and Opera House sunsets",
    shortTagline: "The land of endless wonder Down Under",
    processingTime: "15–25 Business Days",
    startingFee: "AUD $145",
    heroImage: "https://picsum.photos/seed/australia-reef/1920/1080",
    cardImage: "https://picsum.photos/seed/australia-card/600/800",
    successRate: "88%",
    approvalTime: "10–20 Business Days",
    bestTime: "September–November, March–May",
    visaDuration: "3–12 Months",
    accentColor: "#00843D",
    requirements: [
      "Valid passport (valid for entire stay)",
      "Completed online Australia visa (eVisitor/ETA)",
      "Recent passport-size photographs",
      "Proof of financial sufficiency",
      "Accommodation confirmation in Australia",
      "Return flight tickets",
      "Health insurance for duration of stay",
      "Medical examination (if stay > 12 months)",
    ],
    documents: [
      { name: "Passport (original)", required: true },
      { name: "Online Application (ImmiAccount)", required: true },
      { name: "Photographs", required: true },
      { name: "Bank Statement (6 months)", required: true },
      { name: "Hotel/Accommodation Proof", required: true },
      { name: "Return Tickets", required: true },
      { name: "Health Insurance", required: true },
      { name: "Medical Certificate", required: false },
      { name: "Sponsor Letter (if applicable)", required: false },
    ],
    travelTips: [
      "Apply for your visa at least 6 weeks before travel.",
      "Get an Opal card in Sydney for buses, trains and ferries.",
      "Wildlife is not pets — do not hand-feed kangaroos or koalas.",
      "Slip, Slop, Slap: slip on shirt, slop on sunscreen, slap on hat.",
      "Book Uluru sunrise tours well in advance — they sell out fast.",
    ],
    embassy: {
      name: "Australian High Commission, New Delhi",
      address: "1/50-G, Shantipath, Chanakyapuri, New Delhi 110021",
      phone: "+91-11-4139-9900",
      hours: "Monday–Friday: 8:30 AM – 4:30 PM",
    },
  },
];

export const galleryImages = [
  { id: 1, seed: "gallery-temple", label: "Kyoto, Japan", w: 800, h: 600 },
  { id: 2, seed: "gallery-alps", label: "Swiss Alps", w: 600, h: 900 },
  { id: 3, seed: "gallery-paris", label: "Paris, France", w: 800, h: 500 },
  { id: 4, seed: "gallery-venice", label: "Venice, Italy", w: 700, h: 900 },
  { id: 5, seed: "gallery-burj", label: "Dubai, UAE", w: 800, h: 600 },
  { id: 6, seed: "gallery-sydney", label: "Sydney, Australia", w: 600, h: 800 },
  { id: 7, seed: "gallery-sakura", label: "Hiroshima, Japan", w: 800, h: 550 },
  { id: 8, seed: "gallery-zurich", label: "Zurich, Switzerland", w: 700, h: 900 },
  { id: 9, seed: "gallery-amalfi", label: "Amalfi Coast, Italy", w: 800, h: 600 },
  { id: 10, seed: "gallery-desert", label: "Arabian Desert, Dubai", w: 600, h: 800 },
  { id: 11, seed: "gallery-reef", label: "Great Barrier Reef", w: 800, h: 600 },
  { id: 12, seed: "gallery-mont", label: "Mont Blanc, France", w: 700, h: 900 },
];

export const faqs = [
  {
    q: "How early should I apply for a visa?",
    a: "We recommend applying at least 4–6 weeks before your travel date. For peak travel seasons (summer and holidays), apply 8–10 weeks in advance to avoid delays.",
  },
  {
    q: "What if my visa application is rejected?",
    a: "Our team analyses the reason for rejection and helps you reapply with a stronger application. We have a 95%+ success rate on reapplications handled by K2 Journeys.",
  },
  {
    q: "Do I need travel insurance for a visa?",
    a: "Yes — most countries (especially Schengen nations) mandate travel insurance with a minimum coverage of €30,000. We can help you get a policy that meets visa requirements.",
  },
  {
    q: "Can K2 Journeys apply on my behalf?",
    a: "Absolutely. We handle the entire paperwork, application submission, and embassy communication. You only need to provide the documents — we do the rest.",
  },
  {
    q: "Is my passport data safe with K2 Journeys?",
    a: "Yes. We use bank-grade encryption for all document uploads and strictly follow data privacy regulations. Your documents are deleted from our servers 30 days after visa processing.",
  },
  {
    q: "What is the success rate for visa applications?",
    a: "Our overall visa approval rate is 94.7%, significantly higher than the industry average. We pre-screen every application before submission to identify and resolve issues.",
  },
  {
    q: "Do you offer emergency/urgent visa processing?",
    a: "Yes, we offer express visa processing for most destinations. Emergency processing is available for select countries with a 24–72 hour turnaround, subject to availability.",
  },
];
